/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class BufferedPortImageRgbFloat extends Contactable {
  private long swigCPtr;

  protected BufferedPortImageRgbFloat(long cPtr, boolean cMemoryOwn) {
    super(yarpJNI.BufferedPortImageRgbFloat_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BufferedPortImageRgbFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_BufferedPortImageRgbFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BufferedPortImageRgbFloat() {
    this(yarpJNI.new_BufferedPortImageRgbFloat(), true);
  }

  public boolean addOutput(String name) {
    return yarpJNI.BufferedPortImageRgbFloat_addOutput__SWIG_0(swigCPtr, this, name);
  }

  public boolean addOutput(String name, String carrier) {
    return yarpJNI.BufferedPortImageRgbFloat_addOutput__SWIG_1(swigCPtr, this, name, carrier);
  }

  public boolean addOutput(Contact contact) {
    return yarpJNI.BufferedPortImageRgbFloat_addOutput__SWIG_2(swigCPtr, this, Contact.getCPtr(contact), contact);
  }

  public void close() {
    yarpJNI.BufferedPortImageRgbFloat_close(swigCPtr, this);
  }

  public void interrupt() {
    yarpJNI.BufferedPortImageRgbFloat_interrupt(swigCPtr, this);
  }

  public void resume() {
    yarpJNI.BufferedPortImageRgbFloat_resume(swigCPtr, this);
  }

  public int getPendingReads() {
    return yarpJNI.BufferedPortImageRgbFloat_getPendingReads(swigCPtr, this);
  }

  public Contact where() {
    return new Contact(yarpJNI.BufferedPortImageRgbFloat_where(swigCPtr, this), true);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.BufferedPortImageRgbFloat_getName(swigCPtr, this), true);
  }

  public ImageRgbFloat prepare() {
    return new ImageRgbFloat(yarpJNI.BufferedPortImageRgbFloat_prepare(swigCPtr, this), false);
  }

  public boolean unprepare() {
    return yarpJNI.BufferedPortImageRgbFloat_unprepare(swigCPtr, this);
  }

  public void write(boolean forceStrict) {
    yarpJNI.BufferedPortImageRgbFloat_write__SWIG_0(swigCPtr, this, forceStrict);
  }

  public void write() {
    yarpJNI.BufferedPortImageRgbFloat_write__SWIG_1(swigCPtr, this);
  }

  public void writeStrict() {
    yarpJNI.BufferedPortImageRgbFloat_writeStrict(swigCPtr, this);
  }

  public void setStrict(boolean strict) {
    yarpJNI.BufferedPortImageRgbFloat_setStrict__SWIG_0(swigCPtr, this, strict);
  }

  public void setStrict() {
    yarpJNI.BufferedPortImageRgbFloat_setStrict__SWIG_1(swigCPtr, this);
  }

  public ImageRgbFloat read(boolean shouldWait) {
    long cPtr = yarpJNI.BufferedPortImageRgbFloat_read__SWIG_0(swigCPtr, this, shouldWait);
    return (cPtr == 0) ? null : new ImageRgbFloat(cPtr, false);
  }

  public ImageRgbFloat read() {
    long cPtr = yarpJNI.BufferedPortImageRgbFloat_read__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgbFloat(cPtr, false);
  }

  public ImageRgbFloat lastRead() {
    long cPtr = yarpJNI.BufferedPortImageRgbFloat_lastRead(swigCPtr, this);
    return (cPtr == 0) ? null : new ImageRgbFloat(cPtr, false);
  }

  public boolean isClosed() {
    return yarpJNI.BufferedPortImageRgbFloat_isClosed(swigCPtr, this);
  }

  public void setReplier(PortReader reader) {
    yarpJNI.BufferedPortImageRgbFloat_setReplier(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void setReader(PortReader reader) {
    yarpJNI.BufferedPortImageRgbFloat_setReader(swigCPtr, this, PortReader.getCPtr(reader), reader);
  }

  public void onRead(ImageRgbFloat datum) {
    yarpJNI.BufferedPortImageRgbFloat_onRead(swigCPtr, this, ImageRgbFloat.getCPtr(datum), datum);
  }

  public void useCallback(TypedReaderCallbackImageRgbFloat callback) {
    yarpJNI.BufferedPortImageRgbFloat_useCallback__SWIG_0(swigCPtr, this, TypedReaderCallbackImageRgbFloat.getCPtr(callback), callback);
  }

  public void useCallback() {
    yarpJNI.BufferedPortImageRgbFloat_useCallback__SWIG_1(swigCPtr, this);
  }

  public void disableCallback() {
    yarpJNI.BufferedPortImageRgbFloat_disableCallback(swigCPtr, this);
  }

  public boolean setEnvelope(PortWriter envelope) {
    return yarpJNI.BufferedPortImageRgbFloat_setEnvelope(swigCPtr, this, PortWriter.getCPtr(envelope), envelope);
  }

  public boolean getEnvelope(PortReader envelope) {
    return yarpJNI.BufferedPortImageRgbFloat_getEnvelope(swigCPtr, this, PortReader.getCPtr(envelope), envelope);
  }

  public int getInputCount() {
    return yarpJNI.BufferedPortImageRgbFloat_getInputCount(swigCPtr, this);
  }

  public int getOutputCount() {
    return yarpJNI.BufferedPortImageRgbFloat_getOutputCount(swigCPtr, this);
  }

  public boolean isWriting() {
    return yarpJNI.BufferedPortImageRgbFloat_isWriting(swigCPtr, this);
  }

  public void getReport(PortReport reporter) {
    yarpJNI.BufferedPortImageRgbFloat_getReport(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public void setReporter(PortReport reporter) {
    yarpJNI.BufferedPortImageRgbFloat_setReporter(swigCPtr, this, PortReport.getCPtr(reporter), reporter);
  }

  public SWIGTYPE_p_void acquire() {
    long cPtr = yarpJNI.BufferedPortImageRgbFloat_acquire(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void release(SWIGTYPE_p_void handle) {
    yarpJNI.BufferedPortImageRgbFloat_release(swigCPtr, this, SWIGTYPE_p_void.getCPtr(handle));
  }

  public void setTargetPeriod(double period) {
    yarpJNI.BufferedPortImageRgbFloat_setTargetPeriod(swigCPtr, this, period);
  }

}
