/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class Contact {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Contact(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Contact obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_Contact(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Contact empty() {
    return new Contact(yarpJNI.Contact_empty(), true);
  }

  public static Contact invalid() {
    return new Contact(yarpJNI.Contact_invalid(), true);
  }

  public static Contact byName(String name) {
    return new Contact(yarpJNI.Contact_byName(name), true);
  }

  public static Contact byCarrier(String carrier) {
    return new Contact(yarpJNI.Contact_byCarrier(carrier), true);
  }

  public static Contact byConfig(SWIGTYPE_p_Searchable config) {
    return new Contact(yarpJNI.Contact_byConfig(SWIGTYPE_p_Searchable.getCPtr(config)), true);
  }

  public Contact addCarrier(String carrier) {
    return new Contact(yarpJNI.Contact_addCarrier(swigCPtr, this, carrier), true);
  }

  public static Contact bySocket(String carrier, String host, int portNumber) {
    return new Contact(yarpJNI.Contact_bySocket(carrier, host, portNumber), true);
  }

  public Contact addSocket(String carrier, String host, int portNumber) {
    return new Contact(yarpJNI.Contact_addSocket(swigCPtr, this, carrier, host, portNumber), true);
  }

  public Contact addName(String name) {
    return new Contact(yarpJNI.Contact_addName(swigCPtr, this, name), true);
  }

  public static ConstString convertHostToIp(String name) {
    return new ConstString(yarpJNI.Contact_convertHostToIp(name), true);
  }

  public Contact(Contact alt) {
    this(yarpJNI.new_Contact__SWIG_0(Contact.getCPtr(alt), alt), true);
  }

  public ConstString getName() {
    return new ConstString(yarpJNI.Contact_getName(swigCPtr, this), true);
  }

  public ConstString getHost() {
    return new ConstString(yarpJNI.Contact_getHost(swigCPtr, this), true);
  }

  public ConstString getCarrier() {
    return new ConstString(yarpJNI.Contact_getCarrier(swigCPtr, this), true);
  }

  public int getPort() {
    return yarpJNI.Contact_getPort(swigCPtr, this);
  }

  public ConstString toString_c() {
    return new ConstString(yarpJNI.Contact_toString_c(swigCPtr, this), true);
  }

  public static Contact fromString(String txt) {
    return new Contact(yarpJNI.Contact_fromString(txt), true);
  }

  public boolean isValid() {
    return yarpJNI.Contact_isValid(swigCPtr, this);
  }

  public Contact() {
    this(yarpJNI.new_Contact__SWIG_1(), true);
  }

}
