/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yarp;

public class NameStore {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NameStore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NameStore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yarpJNI.delete_NameStore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Contact query(String name) {
    return new Contact(yarpJNI.NameStore_query(swigCPtr, this, name), true);
  }

  public boolean announce(String name, int activity) {
    return yarpJNI.NameStore_announce(swigCPtr, this, name, activity);
  }

}
